version: "2.1"
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    volumes:
      - ./config:/docker-entrypoint-initdb.d
    expose:
      - "3306"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p12345678"]
      interval: 5s
      timeout: 1s
      retries: 100

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy

    restart: always
    links:
      - db:db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/restapi?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678

  frontend:
    build: ./frontend
    depends_on:
      - db
      - backend
    restart: always
    links:
      - backend:backend
    ports:
      - 8090:80